services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.6
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:8.18.6
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./src/main/java/com/dinidu/pms/logstash/pipeline:/usr/share/logstash/pipeline:ro
      - logstash_data:/usr/share/logstash/data
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - elastic
    entrypoint: >
      sh -c "
        until curl -s http://elasticsearch:9200 >/dev/null; do
          echo 'Waiting for Elasticsearch...';
          sleep 5;
        done;
        /usr/local/bin/docker-entrypoint
      "

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.6
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.18.6
    container_name: apm-server
    depends_on:
      - elasticsearch
    environment:
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]
      - apm-server.kibana.enabled=true
      - apm-server.kibana.host=http://kibana:5601
    ports:
      - "8200:8200"
    networks:
      - elastic


volumes:
  es_data:
    driver: local
  logstash_data:
    driver: local

networks:
  elastic:
    driver: bridge
